run:
  tests: true

linters-settings:
  depguard:
    list-type: allow
    packages:
      - github.com/Konstanta100/BrokerCalculator/internal/config
      - github.com/russianinvestments/invest-api-go-sdk/...
      - github.com/caarlos0/env/v11
      - github.com/joho/godotenv
      - github.com/jackc/pgx/v5/pgtype
      - fmt
      - net/http
    include-go-root: true
  funlen:
    lines: 150
    statements: 80

linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errorlint
    - exhaustive
    - exportloopref
    - funlen
    - gci
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - gofumpt
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ifshort
    - importas
    - ineffassign
    - lll
    - makezero
    - misspell
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - structcheck
    - stylecheck
    - tagliatelle
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - wastedassign
    - whitespace