// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID          string           `db:"id" json:"id"`
	UserID      pgtype.UUID      `db:"user_id" json:"user_id"`
	Name        string           `db:"name" json:"name"`
	Status      string           `db:"status" json:"status"`
	Type        string           `db:"type" json:"type"`
	AccessLevel string           `db:"access_level" json:"access_level"`
	OpenedDate  pgtype.Timestamp `db:"opened_date" json:"opened_date"`
	ClosedDate  pgtype.Timestamp `db:"closed_date" json:"closed_date"`
}

type Operation struct {
	ID             string           `db:"id" json:"id"`
	AccountID      string           `db:"account_id" json:"account_id"`
	Figi           string           `db:"figi" json:"figi"`
	InstrumentType string           `db:"instrument_type" json:"instrument_type"`
	Payment        pgtype.Numeric   `db:"payment" json:"payment"`
	Quantity       int64            `db:"quantity" json:"quantity"`
	Currency       string           `db:"currency" json:"currency"`
	Date           pgtype.Timestamp `db:"date" json:"date"`
}

type User struct {
	ID    pgtype.UUID `db:"id" json:"id"`
	Name  string      `db:"name" json:"name"`
	Email string      `db:"email" json:"email"`
}
