// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AccountById(ctx context.Context, id string) (*Account, error)
	AccountCreate(ctx context.Context, arg AccountCreateParams) (string, error)
	AccountsByUserId(ctx context.Context, userID pgtype.UUID) ([]*Account, error)
	BulkInsertOperations(ctx context.Context, arg []BulkInsertOperationsParams) (int64, error)
	OperationCreate(ctx context.Context, arg OperationCreateParams) (string, error)
	OperationsByAccountId(ctx context.Context, accountID string) ([]*Operation, error)
	OperationsByInstrument(ctx context.Context, arg OperationsByInstrumentParams) ([]*Operation, error)
	OperationsByInstrumentAndDateRange(ctx context.Context, arg OperationsByInstrumentAndDateRangeParams) ([]*Operation, error)
	UserById(ctx context.Context, id pgtype.UUID) (*User, error)
	UserCreate(ctx context.Context, arg UserCreateParams) (pgtype.UUID, error)
}

var _ Querier = (*Queries)(nil)
