version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .docker/Dockerfile
    ports:
      - "8182:8182"
    env_file:
      - ../.env
    networks:
      - my_network


networks:
  my_network: